// <auto-generated />
using EfExo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfExo.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfExo.EntitiesConfiguration.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MainActor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Movie");

                    b.HasCheckConstraint("CK_Year", "Year > 1975");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Science-Fiction",
                            Director = "Georges Lucas",
                            MainActor = "Mark Hammil",
                            Title = "Star Wars : Un nouvel espoir",
                            Year = 1977
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Science-Fiction",
                            Director = "Georges Lucas",
                            MainActor = "Mark Hammil",
                            Title = "Star Wars : L'empire contre-attaque",
                            Year = 1980
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Science-Fiction",
                            Director = "Georges Lucas",
                            MainActor = "Mark Hammil",
                            Title = "Star Wars : Le retour du Jedi",
                            Year = 1983
                        },
                        new
                        {
                            MovieId = 4,
                            Category = "Société",
                            Director = "Lexi Alexander",
                            MainActor = "Charlie Hunnam",
                            Title = "Hooligans",
                            Year = 2005
                        },
                        new
                        {
                            MovieId = 5,
                            Category = "Heroic-Fantasy",
                            Director = "Peter Jackson",
                            MainActor = "Elijah Wood",
                            Title = "LOTR - La communauté de l'anneau",
                            Year = 2001
                        },
                        new
                        {
                            MovieId = 6,
                            Category = "Heroic-Fantasy",
                            Director = "Peter Jackson",
                            MainActor = "Elijah Wood",
                            Title = "LOTR - Les deux tours",
                            Year = 2002
                        },
                        new
                        {
                            MovieId = 7,
                            Category = "Heroic-Fantasy",
                            Director = "Peter Jackson",
                            MainActor = "Elijah Wood",
                            Title = "LOTR - Le retour du roi",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
