// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using toolbox_api.Database;

namespace toolbox_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210508102344_CategoryLanguage")]
    partial class CategoryLanguage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("toolbox_api.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryID");

                    b.HasIndex("ToolID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("toolbox_api.Models.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LanguageID");

                    b.HasIndex("ToolID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("toolbox_api.Models.Tool", b =>
                {
                    b.Property<int>("ToolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ToolID");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("toolbox_api.Models.Category", b =>
                {
                    b.HasOne("toolbox_api.Models.Tool", null)
                        .WithMany("Category")
                        .HasForeignKey("ToolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("toolbox_api.Models.Language", b =>
                {
                    b.HasOne("toolbox_api.Models.Tool", null)
                        .WithMany("Language")
                        .HasForeignKey("ToolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("toolbox_api.Models.Tool", b =>
                {
                    b.Navigation("Category");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
